// Dashboard filtering bar action
export const INIT_MENU_FILTERS = 'INIT_MENU_FILTERS';
export const REQUEST_MENU_FILTERS = 'REQUEST_MENU_FILTERS';
export const RECEIVE_MENU_FILTERS = 'RECEIVE_MENU_FILTERS';
export const ERROR_MENU_FILTERS = 'ERROR_MENU_FILTERS';
export const SELECT_MENU_FILTERS = 'SELECT_MENU_FILTERS';
export const SUBMIT_MENU_FILTERS = 'SUBMIT_MENU_FILTERS';

// Dashboard content actions
export const INIT_FILTERED_DATA_LOAD = 'INIT_FILTERED_DATA_LOAD';
export const START_FILTERED_DATA_LOAD = 'START_FILTERED_DATA_LOAD';
export const FINISH_FILTERED_DATA_LOAD = 'FINISH_FILTERED_DATA_LOAD';
export const ERROR_FILTERED_DATA_LOAD = 'ERROR_FILTERED_DATA_LOAD';

// Country generic data actions
export const INIT_COUNTRY_GENERIC_DATA_LOAD = 'INIT_COUNTRY_GENERIC_DATA_LOAD';
export const START_COUNTRY_GENERIC_DATA_LOAD =
  'START_COUNTRY_GENERIC_DATA_LOAD';
export const FINISH_COUNTRY_GENERIC_DATA_LOAD =
  'FINISH_COUNTRY_GENERIC_DATA_LOAD';
export const ERROR_COUNTRY_GENERIC_DATA_LOAD =
  'ERROR_COUNTRY_GENERIC_DATA_LOAD';

// Home-page forecats actions
export const INIT_FORECAST_DATA_LOAD = 'INIT_FORECAST_DATA_LOAD';
export const START_FORECAST_DATA_LOAD = 'START_FORECAST_DATA_LOAD';
export const FINISH_FORECAST_DATA_LOAD = 'FINISH_FORECAST_DATA_LOAD';
export const ERROR_FORECAST_DATA_LOAD = 'ERROR_FORECAST_DATA_LOAD';
export const INIT_USER_FORECAST_DATA_LOAD = 'INIT_USER_FORECAST_DATA_LOAD';
export const START_USER_FORECAST_DATA_LOAD = 'START_USER_FORECAST_DATA_LOAD';
export const FINISH_USER_FORECAST_DATA_LOAD = 'FINISH_USER_FORECAST_DATA_LOAD';
export const ERROR_USER_FORECAST_DATA_LOAD = 'ERROR_USER_FORECAST_DATA_LOAD';

export const INIT_SCENARIO_DATA_LOAD = 'INIT_SCENARIO_DATA_LOAD';
export const START_SCENARIO_DATA_LOAD = 'START_SCENARIO_DATA_LOAD';
export const FINISH_SCENARIO_DATA_LOAD = 'FINISH_SCENARIO_DATA_LOAD';
export const ERROR_SCENARIO_DATA_LOAD = 'ERROR_SCENARIO_DATA_LOAD';

// Home-page data-trends actions
export const INIT_DATA_TRENDS_LOAD = 'INIT_DATA_TRENDS_LOAD';
export const START_DATA_TRENDS_LOAD = 'START_DATA_TRENDS_LOAD';
export const FINISH_DATA_TRENDS_LOAD = 'FINISH_DATA_TRENDS_LOAD';
export const ERROR_DATA_TRENDS_LOAD = 'ERROR_DATA_TRENDS_LOAD';
export const INIT_DATA_TRENDS_META_LOAD = 'INIT_DATA_TRENDS_META_LOAD';
export const START_DATA_TRENDS_META_LOAD = 'START_DATA_TRENDS_META_LOAD';
export const FINISH_DATA_TRENDS_META_LOAD = 'FINISH_DATA_TRENDS_META_LOAD';
export const ERROR_DATA_TRENDS_META_LOAD = 'ERROR_DATA_TRENDS_META_LOAD';

export const INIT_MAP_DATA_LOAD = 'INIT_MAP_DATA_LOAD';
export const START_MAP_DATA_LOAD = 'START_MAP_DATA_LOAD';
export const FINISH_MAP_DATA_LOAD = 'FINISH_MAP_DATA_LOAD';
export const ERROR_MAP_DATA_LOAD = 'ERROR_MAP_DATA_LOAD';

export const INIT_USER_LIST_DATA_LOAD = 'INIT_USER_LIST_DATA_LOAD';
export const START_USER_LIST_DATA_LOAD = 'START_USER_LIST_DATA_LOAD';
export const FINISH_USER_LIST_DATA_LOAD = 'FINISH_USER_LIST_DATA_LOAD';
export const ERROR_USER_LIST_DATA_LOAD = 'ERROR_USER_LIST_DATA_LOAD';

export const INIT_USER_DATA_LOAD = 'INIT_USER_DATA_LOAD';
export const START_USER_DATA_LOAD = 'START_USER_DATA_LOAD';
export const FINISH_USER_DATA_LOAD = 'FINISH_USER_DATA_LOAD';
export const ERROR_USER_DATA_LOAD = 'ERROR_USER_DATA_LOAD';

export const INIT_MODAL = 'INIT_MODAL';
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';

export const INIT_USER_ACTION = 'INIT_USER_ACTION';
export const START_USER_ACTION_EDIT = 'START_USER_ACTION_EDIT';
export const START_USER_ACTION_CREATE = 'START_USER_ACTION_CREATE';
export const START_USER_ACTION_DELETE = 'START_USER_ACTION_DELETE';
export const ERROR_USER_ACTION = 'ERROR_USER_ACTION';

export const INIT_CHART_LOAD = 'INIT_PIE_CHART_LOAD';
export const START_CHART_LOAD = 'START_PIE_CHART_LOAD';
export const FINISH_CHART_LOAD = 'FINISH_PIE_CHART_LOAD';

export const INIT_MAP_LOAD = 'INIT_MAP_LOAD';
export const START_MAP_LOAD = 'START_MAP_LOAD';

export const INIT_SAR_LOAD = 'INIT_SAR_LOAD';
export const START_SAR_LOAD = 'START_SAR_LOAD';
export const FINISH_SAR_LOAD = 'FINISH_SAR_LOAD';
export const ERROR_SAR_LOAD = 'ERROR_SAR_LOAD';
export const INIT_SINGLE_SAR_LOAD = 'INIT_SINGLE_SAR_LOAD';
export const START_SINGLE_SAR_LOAD = 'START_SINGLE_SAR_LOAD';
export const FINISH_SINGLE_SAR_LOAD = 'FINISH_SINGLE_SAR_LOAD';
export const ERROR_SINGLE_SAR_LOAD = 'ERROR_SINGLE_SAR_LOAD';
export const SAVE_SAR_IMAGE = 'SAVE_SAR_IMAGE';

export const INIT_INDICATORS_LOAD = 'INIT_INDICATORS_LOAD';
export const START_INDICATORS_LOAD = 'START_INDICATORS_LOAD';
export const FINISH_INDICATORS_LOAD = 'FINISH_INDICATORS_LOAD';
export const ERROR_INDICATORS_LOAD = 'ERROR_INDICATORS_LOAD';

export const INIT_CAUSALITY_DEMO_LOAD = 'INIT_CAUSALITY_DEMO_LOAD';
export const START_CAUSALITY_DEMO_LOAD = 'START_CAUSALITY_DEMO_LOAD';
export const FINISH_CAUSALITY_DEMO_LOAD = 'FINISH_CAUSALITY_DEMO_LOAD';
export const ERROR_CAUSALITY_DEMO_LOAD = 'ERROR_CAUSALITY_DEMO_LOAD';

export const INIT_CAUSALITY_MARGINALS_LOAD = 'INIT_CAUSALITY_MARGINALS_LOAD';
export const START_CAUSALITY_MARGINALS_LOAD = 'START_CAUSALITY_MARGINALS_LOAD';
export const FINISH_CAUSALITY_MARGINALS_LOAD =
  'FINISH_CAUSALITY_MARGINALS_LOAD';
export const ERROR_CAUSALITY_MARGINALS_LOAD = 'ERROR_CAUSALITY_MARGINALS_LOAD';

export const INIT_CAUSALITY_META_LOAD = 'INIT_CAUSALITY_META_LOAD';
export const START_CAUSALITY_META_LOAD = 'START_CAUSALITY_META_LOAD';
export const FINISH_CAUSALITY_META_LOAD = 'FINISH_CAUSALITY_META_LOAD';
export const ERROR_CAUSALITY_META_LOAD = 'ERROR_CAUSALITY_META_LOAD';
export const STASH_CURRENT_CAUSALITY_DEMO = 'STASH_CURRENT_CAUSALITY_DEMO';
export const UNSTASH_CAUSALITY_DEMO = 'UNSTASH_CAUSALITY_DEMO';
export const UPDATE_CAUSALITY_MARGINALS = 'UPDATE_CAUSALITY_MARGINALS';
export const SELECT_CAUSALITY_MARGINALS = 'SELECT_CAUSALITY_MARGINALS';
export const SET_LOADING_CAUSALITY_DIMENSION =
  'SET_LOADING_CAUSALITY_DIMENSION';
export const RESET_LOADING_CAUSALITY_DIMENSION =
  'RESET_LOADING_CAUSALITY_DIMENSION';
export const CAUSALITY_DIMENSION_CLICKED = 'CAUSALITY_DIMENSION_CLICKED';
export const CAUSALITY_OBSERVATIONS_SELECTED =
  'CAUSALITY_OBSERVATIONS_SELECTED';
export const CAUSALITY_UPDATE_SELECTION = 'CAUSALITY_UPDATE_SELECTION';
export const CAUSALITY_CLEAN_SELECTION = 'CAUSALITY_CLEAN_SELECTION';
export const FINISH_CAUSALITY_LOAD = 'FINISH_CAUSALITY_LOAD';
